### ISSUE TITLE
Help: How to deal with graphic assets

### ISSUE THREAD

**Issue by hansipete** [arnoson/kirby-vite-basic-kit#2]
Hello! Thank you for that great plugin. Superhappy with it, just works perfectly.

I am not sure how to deal with assets though. As long as they're called from css, js files – no problem. But I do have a few svgs that get included in my template (logo for header, etc.).

For now I added a `public/assets/` folder manually. But this feels a bit inconsistent...

How to do it properly?

Thank you,
Hans

**Comment by arnoson** [comment]
Gald you like it!
Creating the `public/assets/` folder manually is the way to go! See this similar [issue](https://github.com/arnoson/kirby-vite-multi-page-kit/issues/10) in the multi page kit. Since you don't reference these specific assets from js/css vite can't know about them and so they are just normal kirby assets. Maybe there is some other way make them known to vite and use them with a special helper function from within php, but I'm not sure if this is worth investigating/implementing at the moment.

**Comment by arnoson** [comment]
You could also use a [public folder with vite](https://vitejs.dev/guide/assets.html#the-public-directory) or the [vite-plugin-static-copy](https://www.npmjs.com/package/vite-plugin-static-copy) if you want to consistently place all your assets inside the src folder. Closing this issue now as its not really an issue with this starter kit.
